### ISSUE TITLE
Self-supervised Learning Fundamentals & Related Work

### ISSUE THREAD

**Issue by sven-luepke** [KnightTec/mlmi-project#2]
## Tasks
- [ ] Explain the general principles and motivation behind self-supervised learning.
- [ ] Find and understand at least 2 influential papers (with a high citation count) related to self-supervised learning.
- [ ] Clearly state the motivation behind each paper and the problem it attempts to solve in the context of self-supervised learning.
- [ ] Find common evaluation metrics.

### Self-supervised pre-training tasks of transformers [3] TODO: imaging equivalents
1. Language Modeling (LM)
2. Causal Language Modeling (Causality-masked LM)
3. Prefix Language Modeling (Prefix LM)
4. Masked Language Modeling (MLM)
5. Permuted Language Modeling (PLM)
6. Denoising Autoencoder (DAE)
7. Replaced Token Detection (RTD)
8. Next Sentence Prediction (NSP)

### References
1. https://ai.facebook.com/blog/self-supervised-learning-practical-guide/
2. https://ai.facebook.com/blog/new-ai-research-to-help-predict-covid-19-resource-needs-from-a-series-of-x-rays/
3. [Pre-trained Models for Natural Language Processing: A Survey](https://arxiv.org/abs/2003.08271)
