### ISSUE TITLE
Representation Learning Fundamentals & Related Work

### ISSUE THREAD

**Issue by sven-luepke** [KnightTec/mlmi-project#3]
### Tasks
- [ ] Explain the principles and motivation behind representation learning.
- [ ] Find and understand at least 2 influential papers (with a high citation count) related to **Representation Learning**
- [ ] Clearly state the motivation behind each paper and the problem it attempts to solve in the context of **Representation Learning**
- [ ] Find common evaluation metrics

### Notes
- pre-training models such as BERT are essentially about learning representations
- knowledge destillation with teacher-student setting (DistilBERT)
- using different encoders (BERT, CLIP) to condition a generative (diffusion) model
- BERT is a contextual encoder
- "pre-trained representations reduce the need for many heavily-engineered task-specific architectures" [1]
- ELMo is feature based (what does that mean?)
- BERT: first supervised pre-training followed by supervised fine tuning using labelled data (with or without base model freezing)
- BERT use two training objectives: masked language modelling (MLM) to ensure that the represetations capture context, and next sentence prediction to capture the relationship between sentences. Thus, the choice of training objective can be used to guide the information captured by the representations
- transfer learning is a specific type of representation learning

### References
 1. [BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding](https://arxiv.org/abs/1810.04805)
 2. [GPT-3: Language Models are Few-Shot Learners](https://arxiv.org/abs/2005.14165)
 3. [Advancing Self-Supervised and Semi-Supervised Learning with SimCLR](https://ai.googleblog.com/2020/04/advancing-self-supervised-and-semi.html)
 4. [ELMo: Deep contextualized word representations](https://arxiv.org/abs/1802.05365)
