### ISSUE TITLE
Multimodal Representations Fundamentals & Related Work

### ISSUE THREAD

**Issue by sven-luepke** [KnightTec/mlmi-project#4]
## Tasks
- [ ] Explain the principles and motivation behind multimodal representations.
- [ ] Find and understand at least 2 influential papers (with a high citation count) related to **Multimodal Representations**
- [ ] Clearly state the motivation behind each paper and the problem it attempts to solve in the context of **Multimodal Representations**
- [ ] Find common evaluation metrics.

### References
