### ISSUE TITLE
Self-Supervised Multimodal Representation Learning Fundamentals & Related Work

### ISSUE THREAD

**Issue by sven-luepke** [KnightTec/mlmi-project#5]
### Tasks
- [ ] Find and understand at least 2 influential papers (with a high citation count) related to **Self-Supervised Multimodal Representation**.
- [ ] Clearly state the motivation behind each paper and the problem it attempts to solve in the context of **Self-Supervised Multimodal Representation**.
- [ ] Find common evaluation metrics.

### Notes
- TODO

# References
