### ISSUE TITLE
Self-Supervised Multimodal Representation Learning SOTA

### ISSUE THREAD

**Issue by sven-luepke** [KnightTec/mlmi-project#6]
## Tasks

- [ ] Find at least 3 state-of-the-art methods for different applications self-supervised multimodal representation learning, ideally in the the medical field
- [ ] Using the metrics from the related work show how much it improves upon it
- [ ] Explain what differences in SOTA compared to the previous work are responsible for the performance improvements
